import { describe, it, expect } from 'vitest';
import { parseGcode } from '../src/parse/parseGcode';
import { detectMode } from '../src/parse/detectMode';

const FDM = [
  ';FLAVOR:Marlin',
  '; generated by Cura_SteamEngine',
  ';LAYER_COUNT:2',
  'M104 S200',
  'M140 S60',
  'M109 S200',
  'M106 S255',
  'G21',
  'G90',
  'M82',
  'G92 E0',
  ';LAYER:0',
  ';TYPE:WALL-OUTER',
  'G1 X10 Y0 E1 F1500',
  'G1 X20 Y0 E2',
  ';LAYER:1',
  'G1 Z0.4',
  'G1 X20 Y10 E3',
].join('\n');

const CNC = [
  '(GRBL post processor)',
  'G20',
  'G90',
  'G54',
  'T1 M6',
  'G43 H1',
  'M3 S12000',
  'M8',
  'G0 X0 Y0 Z0.25',
  'G1 Z-0.1 F5',
  'G1 X1 Y0 F10',
  'G2 X2 Y1 I0 J1',
  'M5',
  'M9',
  'M30',
].join('\n');

describe('detectMode — additive', () => {
  it('scores an FDM snippet as additive', () => {
    const doc = parseGcode(FDM);
    const det = detectMode(doc.moves, FDM);
    expect(det.mode).toBe('additive');
    expect(det.additiveScore).toBeGreaterThan(det.subtractiveScore);
    expect(det.reasons.join(' | ')).toMatch(/extrud|temperature|slicer/i);
    // parseGcode should agree.
    expect(doc.mode).toBe('additive');
  });
});

describe('detectMode — subtractive', () => {
  it('scores a CNC snippet as subtractive', () => {
    const doc = parseGcode(CNC);
    const det = detectMode(doc.moves, CNC);
    expect(det.mode).toBe('subtractive');
    expect(det.subtractiveScore).toBeGreaterThan(det.additiveScore);
    expect(det.reasons.join(' | ')).toMatch(/spindle|tool change|imperial|offset/i);
    expect(doc.mode).toBe('subtractive');
  });

  it('the CNC snippet has no extrusion and carries spindle/tool data', () => {
    const doc = parseGcode(CNC);
    expect(doc.moves.every((m) => (m.extrude ?? 0) === 0)).toBe(true);
    expect(doc.meta.tools).toContain(1);
    const spindled = doc.moves.filter((m) => (m.spindle ?? 0) > 0);
    expect(spindled.length).toBeGreaterThan(0);
  });
});
