// ---------------------------------------------------------------------------
// Mode auto-detection. Scores a parsed move stream + raw text for additive
// (FDM) vs subtractive (CNC) signals and returns the chosen mode with
// human-readable reasons. Pure; safe in workers and tests.
// ---------------------------------------------------------------------------

import { isExtruding, type Move, type ModeDetection } from '../types';

/**
 * Decide whether a G-code program is an additive (3D print) or subtractive
 * (CNC mill) job. Both the normalized moves and the raw text are inspected:
 * moves give reliable extrusion/spindle signals, the raw text catches M-codes,
 * slicer headers and modal G-codes that the IR does not retain.
 */
export function detectMode(moves: Move[], rawText: string): ModeDetection {
  const reasons: string[] = [];
  let additive = 0;
  let subtractive = 0;

  // --- signals from the normalized moves --------------------------------
  let extrudingMoves = 0;
  let spindleMoves = 0;
  for (const m of moves) {
    if (isExtruding(m)) extrudingMoves++;
    if (m.spindle !== undefined && m.spindle > 0) spindleMoves++;
  }

  if (extrudingMoves > 0) {
    additive += 5;
    reasons.push(`${extrudingMoves} extruding G1 moves (E>0)`);
  }
  if (spindleMoves > 0) {
    subtractive += 3;
    reasons.push(`${spindleMoves} moves with spindle on (S>0)`);
  }

  // Toolpath that never extrudes anywhere is a hint toward subtractive.
  if (moves.length > 0 && extrudingMoves === 0) {
    subtractive += 2;
    reasons.push('no extrusion present (no E)');
  }

  // --- signals from raw text -------------------------------------------
  // Scan line-by-line so word boundaries are respected and comments count.
  const lines = rawText.split(/\r?\n/);

  let sawTemp = false;
  let sawFan = false;
  let sawSpindleCmd = false;
  let sawToolChange = false;
  let sawInches = false;
  let sawCoolant = false;
  let sawWorkOffset = false;
  let sawTLO = false;
  let sawBedLevel = false;
  let sawSlicerHeader = false;

  for (const raw of lines) {
    // Code portion (before any comment) for M/G word matching.
    const code = raw.replace(/;.*$/, '').replace(/\([^)]*\)/g, '').toUpperCase();
    const comment = raw.toUpperCase();

    // Additive: temperatures M104/M109 (hotend), M140/M190 (bed).
    if (!sawTemp && /\bM(104|109|140|190)\b/.test(code)) {
      sawTemp = true;
      additive += 4;
      reasons.push('temperature commands (M104/109/140/190)');
    }
    // Additive: fan M106.
    if (!sawFan && /\bM106\b/.test(code)) {
      sawFan = true;
      additive += 2;
      reasons.push('fan control (M106)');
    }
    // Additive: bed levelling probe G29.
    if (!sawBedLevel && /\bG29\b/.test(code)) {
      sawBedLevel = true;
      additive += 1;
      reasons.push('bed levelling (G29)');
    }
    // Additive: slicer headers / markers in comments.
    if (
      !sawSlicerHeader &&
      /;\s*(LAYER:|LAYER_COUNT|TYPE:|CURA|PRUSASLICER|SLIC3R|SUPERSLICER|GENERATED BY|FLAVOR:)/.test(
        comment,
      )
    ) {
      sawSlicerHeader = true;
      additive += 3;
      reasons.push('slicer header/markers (;LAYER:/;TYPE:/Cura/PrusaSlicer)');
    }

    // Subtractive: spindle M3/M4 (and M5 stop implies a spindle exists).
    if (!sawSpindleCmd && /\bM0?[34]\b/.test(code)) {
      sawSpindleCmd = true;
      subtractive += 4;
      reasons.push('spindle start (M3/M4)');
    }
    // Subtractive: tool change M6.
    if (!sawToolChange && /\bM0?6\b/.test(code)) {
      sawToolChange = true;
      subtractive += 3;
      reasons.push('tool change (M6)');
    }
    // Subtractive: inches G20.
    if (!sawInches && /\bG20\b/.test(code)) {
      sawInches = true;
      subtractive += 2;
      reasons.push('imperial units (G20)');
    }
    // Subtractive: coolant M7/M8/M9.
    if (!sawCoolant && /\bM0?[789]\b/.test(code)) {
      sawCoolant = true;
      subtractive += 1;
      reasons.push('coolant control (M7/M8/M9)');
    }
    // Subtractive: work offsets G54–G59.
    if (!sawWorkOffset && /\bG5[4-9]\b/.test(code)) {
      sawWorkOffset = true;
      subtractive += 2;
      reasons.push('work coordinate offsets (G54–G59)');
    }
    // Subtractive: tool length offset G43.
    if (!sawTLO && /\bG43(\.1)?\b/.test(code)) {
      sawTLO = true;
      subtractive += 1;
      reasons.push('tool length offset (G43)');
    }
  }

  const mode = additive >= subtractive ? 'additive' : 'subtractive';
  if (reasons.length === 0) {
    reasons.push('no strong signals; defaulting to additive');
  }

  return {
    additiveScore: additive,
    subtractiveScore: subtractive,
    mode,
    reasons,
  };
}
