// ---------------------------------------------------------------------------
// parseGcode — the pure parse core. Turns raw G-code text into the normalized
// GcodeDoc IR. NO worker/DOM dependencies, so it is directly unit-testable in
// node.
//
// Motion (abs/rel G90/G91, units G20/G21, G92 offset, arc centers from I/J/K)
// is delegated to gcode-toolpath's `Toolpath`, whose addLine/addArcCurve
// callbacks emit start (v1) / end (v2) / center (v0) vectors already resolved
// to absolute millimetres. Per-line E/F/S/T words and header comments — which
// the Toolpath does not surface — are read from a small local tokenizer and
// correlated to each motion by feeding the Toolpath one line at a time.
//
// NB: we deliberately do NOT use cncjs `gcode-parser` for tokenizing — its ESM
// build defines a Node `stream.Transform` subclass at module load, which throws
// ("Super expression must be null or a function") in the browser where Vite
// stubs out `stream`. Tokenizing is trivial, so we inline it; `gcode-toolpath`
// (the valuable motion/arc/units logic) is stream-free and kept.
// ---------------------------------------------------------------------------

import { isExtruding, type GcodeDoc, type Move, type MoveType, type Units, type Vec3, type Box3 } from '../types';
import { detectMode } from './detectMode';

// gcode-toolpath ships no type declarations; the ambient module declaration in
// ./gcode-libs.d.ts describes the slice of its API we use.
import Toolpath from 'gcode-toolpath';

const toVec = (v: { x: number; y: number; z: number }): Vec3 => [v.x, v.y, v.z];

/** A tokenized G-code line: raw text, parsed words, and any comments. */
interface ParsedLine {
  line: string;
  words: [string, number][];
  comments: string[];
}

const WORD_RE = /([A-Za-z])\s*([-+]?(?:\d*\.\d+|\d+\.?))/g;

/**
 * Browser-safe G-code tokenizer. Splits into lines and, per line, pulls out
 * `;…` and `(…)` comments and `Letter+number` words. Matches the shape the rest
 * of this module expects (the slice of cncjs gcode-parser we relied on).
 */
function tokenize(text: string): ParsedLine[] {
  const out: ParsedLine[] = [];
  const lines = text.split('\n');
  for (let raw of lines) {
    if (raw.endsWith('\r')) raw = raw.slice(0, -1);
    const comments: string[] = [];

    // Parenthetical comments (...) anywhere on the line.
    let code = raw.replace(/\(([^)]*)\)/g, (_m, c) => {
      comments.push(String(c).trim());
      return ' ';
    });
    // Semicolon comment to end of line.
    const semi = code.indexOf(';');
    if (semi >= 0) {
      comments.push(code.slice(semi + 1).trim());
      code = code.slice(0, semi);
    }

    const words: [string, number][] = [];
    let m: RegExpExecArray | null;
    WORD_RE.lastIndex = 0;
    while ((m = WORD_RE.exec(code)) !== null) {
      const value = parseFloat(m[2]);
      if (!Number.isNaN(value)) words.push([m[1].toUpperCase(), value]);
    }

    out.push({ line: raw, words, comments });
  }
  return out;
}

function motionToType(motion: string): MoveType | null {
  switch (motion) {
    case 'G0':
      return 'rapid';
    case 'G1':
      return 'cut';
    case 'G2':
      return 'arcCW';
    case 'G3':
      return 'arcCCW';
    default:
      return null;
  }
}

/** Find the value of a single-letter word on a parsed line (last wins). */
function word(words: [string, number][], letter: string): number | undefined {
  let val: number | undefined;
  for (const w of words) {
    if (w[0] === letter) val = w[1];
  }
  return val;
}

/** Extract a generator/slicer name from header comments. */
function detectGenerator(comments: string[]): string | undefined {
  for (const c of comments) {
    const s = c.trim();
    const lc = s.toLowerCase();
    if (lc.includes('cura')) return s;
    if (lc.includes('prusaslicer')) return s;
    if (lc.includes('superslicer')) return s;
    if (lc.includes('slic3r')) return s;
    if (lc.includes('simplify3d')) return s;
    if (lc.includes('ideamaker')) return s;
    if (lc.includes('generated by') || lc.includes('flavor')) return s;
    if (lc.startsWith('fusion') || lc.includes('fusion 360')) return s;
    if (lc.includes('grbl') || lc.includes('post processor') || lc.includes('postprocessor'))
      return s;
  }
  return undefined;
}

/**
 * Parse raw G-code text into the normalized IR. Pure and synchronous.
 */
export function parseGcode(text: string): GcodeDoc {
  const parsed = tokenize(text);
  const lineCount = parsed.length;

  const moves: Move[] = [];

  // bbox accumulation over endpoints of real motion.
  let minX = Infinity,
    minY = Infinity,
    minZ = Infinity;
  let maxX = -Infinity,
    maxY = -Infinity,
    maxZ = -Infinity;
  const grow = (p: Vec3) => {
    if (p[0] < minX) minX = p[0];
    if (p[1] < minY) minY = p[1];
    if (p[2] < minZ) minZ = p[2];
    if (p[0] > maxX) maxX = p[0];
    if (p[1] > maxY) maxY = p[1];
    if (p[2] > maxZ) maxZ = p[2];
  };

  // Modal/word-derived state we track ourselves (the Toolpath does not expose
  // it per callback): feed, spindle speed, declared units, E accounting.
  let curFeed: number | undefined;
  let curSpindle: number | undefined; // last S value seen
  let declaredInches = false; // G20 seen and currently active
  let relativeDistance = false; // G91 active (affects E too)
  let relativeExtrusion = false; // M83 active (E always relative)
  let lastE = 0;

  const toolsSeen = new Set<number>();

  // One shared Toolpath, fed a line at a time so each motion callback maps to a
  // known source line. The callback captures the pending per-line word context.
  let pending: {
    lineNo: number;
    feed?: number;
    spindle?: number;
    extrudeDelta?: number;
    tool?: number;
  } | null = null;

  const onLine = (
    modal: { motion: string },
    v1: { x: number; y: number; z: number },
    v2: { x: number; y: number; z: number },
    v0?: { x: number; y: number; z: number },
  ) => {
    const type = motionToType(modal.motion);
    if (!type || !pending) return;
    const start = toVec(v1);
    const end = toVec(v2);
    const move: Move = {
      type,
      start,
      end,
      lineNo: pending.lineNo,
    };
    if (v0 && (type === 'arcCW' || type === 'arcCCW')) move.center = toVec(v0);
    if (pending.feed !== undefined) move.feed = pending.feed;
    if (pending.extrudeDelta !== undefined) move.extrude = pending.extrudeDelta;
    if (pending.spindle !== undefined) move.spindle = pending.spindle;
    if (pending.tool !== undefined) move.tool = pending.tool;
    moves.push(move);
    grow(start);
    grow(end);
  };

  const tp = new Toolpath({
    addLine: (modal, a, b) => onLine(modal, a, b),
    addArcCurve: (modal, a, b, c) => onLine(modal, a, b, c),
  });

  const allComments: string[] = [];
  const headerComments: string[] = [];

  for (let i = 0; i < parsed.length; i++) {
    const { words, comments } = parsed[i];
    if (comments && comments.length) {
      allComments.push(...comments);
      if (moves.length === 0) headerComments.push(...comments);
    }
    if (!words || words.length === 0) {
      // Comment-only / blank line: still advance the Toolpath (no-op).
      continue;
    }

    // Track distance / extrusion modes from raw words so E deltas are correct.
    const g = collectG(words);
    if (g.has(91)) relativeDistance = true; // G91 → relative positioning
    if (g.has(90)) relativeDistance = false; // G90 → absolute positioning
    if (g.has(20)) declaredInches = true;
    if (g.has(21)) declaredInches = false;

    const m = collectM(words);
    if (m.has(82)) relativeExtrusion = false; // absolute extrusion
    if (m.has(83)) relativeExtrusion = true; // relative extrusion

    // F / S / T words.
    const f = word(words, 'F');
    if (f !== undefined) curFeed = f;
    const s = word(words, 'S');
    if (s !== undefined) curSpindle = s;
    const t = word(words, 'T');
    if (t !== undefined) toolsSeen.add(t);

    // E accounting (extrude delta for this line). G92 resets the E datum.
    let extrudeDelta: number | undefined;
    const e = word(words, 'E');
    if (g.has(92)) {
      // G92 [E0] sets a new datum; no deposition occurs.
      if (e !== undefined) lastE = e;
    } else if (e !== undefined) {
      if (relativeExtrusion || relativeDistance) {
        extrudeDelta = e;
        lastE += e;
      } else {
        extrudeDelta = e - lastE;
        lastE = e;
      }
    }

    // Spindle is only meaningful while the spindle is commanded on. We treat a
    // non-zero S as the active spindle once any M3/M4 has been seen, but to keep
    // the IR simple we attach the last S whenever it is > 0.
    const spindleForMove = curSpindle && curSpindle > 0 ? curSpindle : undefined;

    pending = {
      lineNo: i,
      feed: curFeed,
      spindle: spindleForMove,
      extrudeDelta,
      tool: toolsSeen.size > 0 ? lastTool(words, toolsSeen) : undefined,
    };

    // Feed exactly this line; any motion callback fires synchronously here.
    tp.loadFromStringSync(parsed[i].line);
    pending = null;
  }

  // --- units: declared units. Geometry is always mm (Toolpath converts). ---
  const units: Units = declaredInches ? 'in' : 'mm';

  // --- additive layer banding ----------------------------------------------
  const layerCount = assignLayers(moves);

  // --- bbox -----------------------------------------------------------------
  const bbox: Box3 = moves.length
    ? { min: [minX, minY, minZ], max: [maxX, maxY, maxZ] }
    : { min: [0, 0, 0], max: [0, 0, 0] };

  // --- mode detection -------------------------------------------------------
  const detection = detectMode(moves, text);

  const generator = detectGenerator(headerComments) ?? detectGenerator(allComments);
  const tools = [...toolsSeen].sort((a, b) => a - b);

  return {
    moves,
    units,
    bbox,
    mode: detection.mode,
    meta: {
      generator,
      lineCount,
      layerCount: layerCount > 0 ? layerCount : undefined,
      detection,
      tools: tools.length ? tools : undefined,
    },
  };
}

/** Active tool for a line: explicit T on the line, else the most recent T. */
function lastTool(words: [string, number][], seen: Set<number>): number | undefined {
  const t = word(words, 'T');
  if (t !== undefined) return t;
  if (seen.size === 0) return undefined;
  // Most recently inserted tool.
  let last: number | undefined;
  for (const v of seen) last = v;
  return last;
}

function collectG(words: [string, number][]): Set<number> {
  const s = new Set<number>();
  for (const w of words) if (w[0] === 'G') s.add(w[1]);
  return s;
}

function collectM(words: [string, number][]): Set<number> {
  const s = new Set<number>();
  for (const w of words) if (w[0] === 'M') s.add(w[1]);
  return s;
}

/**
 * Additive Z-banding. Walk the moves; whenever an extruding move appears at a
 * new, strictly-higher Z than the current layer's Z, start a new layer.
 * Non-extruding (travel) moves inherit the current layer. Returns layerCount.
 */
function assignLayers(moves: Move[]): number {
  let layerIndex = -1;
  let layerZ = -Infinity;
  const Z_EPS = 1e-4;

  for (const m of moves) {
    if (isExtruding(m)) {
      const z = m.end[2];
      if (layerIndex < 0 || z > layerZ + Z_EPS) {
        layerIndex++;
        layerZ = z;
      }
      m.layer = layerIndex;
    } else if (layerIndex >= 0) {
      m.layer = layerIndex;
    }
  }
  return layerIndex + 1;
}
